version: '2'

services:
  proxy:
    image: traefik
    command: --web --docker --constraints="tag==exposed"
    networks:
      - webgateway
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml

  landinginfo:
    image: reportportal/landing-aggregator:latest
    networks:
          - webgateway
#    environment:
#      - CONSUMER={{INSERT}}
#      - CONSUMER_SECRET={{INSERT}}
#      - TOKEN={{INSERT}}
#      - TOKEN_SECRET={{INSERT}}
#      - HASHTAG=reportportal_io
    labels:
      - "traefik.backend=landing-info"
      - "traefik.frontend.rule=PathPrefix:/"
      - "traefik.tags=exposed"

networks:
  webgateway:
    driver: bridge