### Get all lists
GET https://{{dc}}.api.mailchimp.com/3.0/lists
Authorization: Bearer {{mailchimpApiKey}}

### Get list members
GET https://{{dc}}.api.mailchimp.com/3.0/lists/{{mailchimpListId}}/members
Authorization: Bearer {{mailchimpApiKey}}

### Get member
GET https://{{dc}}.api.mailchimp.com/3.0/lists/{{mailchimpListId}}/members/{{mailchimpMemberId}}
Authorization: Bearer {{mailchimpApiKey}}

### Add member
POST https://{{dc}}.api.mailchimp.com/3.0/lists/{{mailchimpListId}}/members
Authorization: Bearer {{mailchimpApiKey}}

{
  "email_address": "",
  "status": "pending"
}

### Update member
PUT https://{{dc}}.api.mailchimp.com/3.0/lists/{{mailchimpListId}}/members/{{mailchimpMemberId}}
Authorization: Bearer {{mailchimpApiKey}}

{
  "email_address": "",
  "status": "pending"
}
