@dc = us18

GET https://{{dc}}.api.mailchimp.com/3.0/lists
Authorization: Bearer {{mailchimpApiKey}}

###
POST https://{{dc}}.api.mailchimp.com/3.0/lists/{{mailchimpListId}}/members
  ?skip_merge_validation=true
Authorization: Bearer {{mailchimpApiKey}}

{
  "email_address": "",
  "email_type": "",
  "status": "subscribed",
  "merge_fields": {},
  "interests": {},
  "language": "",
  "vip": false,
  "location": {
    "latitude": 0,
    "longitude": 0
  },
  "marketing_permissions": [],
  "ip_signup": "",
  "timestamp_signup": "",
  "ip_opt": "",
  "timestamp_opt": "",
  "tags": []
}
