@host = localhost
@port = 8080


OPTIONS http://{{host}}:{{port}}/mailchimp/lists/{{mailchimpListId}}/members

###
POST http://{{host}}:{{port}}/mailchimp/lists/{{mailchimpListId}}/members

{
  "email_address": ""
}
